"use client";
import { useEffect, useState } from "react";

type Finding = { item: string; value: string | null; reference_range: string | null; status: "normal" | "abnormal" | "unclear" | "not_reported"; evidence: string };
type Analysis = { document_type?: string; report_date?: string | null; summary?: string; findings?: Finding[]; key_observations?: string[]; supportive_findings?: string[]; limitations_and_concerns?: string[]; possible_associations?: string[]; symptom_associations?: string[]; red_flags?: string[]; questions_for_clinician?: string[]; priority?: string; specialty_hint?: string | null; workflow?: string; confidence?: number; requires_human_review?: boolean };
type Document = { id: string; original_filename: string; content_type: string | null; file_size_bytes: number | null; ocr_status: string; validation_status: string; processing_status?: string; processing_error?: string | null; created_at: string; metadata?: { ai_analysis?: Analysis } };

function priorityLabel(v?: string) { return ({ routine: "Routine review", review_soon: "Review soon", urgent_review: "Urgent human review", unclear: "Priority unclear" } as Record<string, string>)[v || ""] || "Awaiting review"; }
function statusLabel(v?: string) { return (v || "not_reported").replaceAll("_", " "); }
function Section({ title, items }: { title: string; items?: string[] }) { if (!items?.length) return null; return <section className="mt-5"><h4 className="border-b border-[#0b5960]/15 pb-1 text-[9px] font-black uppercase tracking-[.18em] text-[#0b5960]">{title}</h4><ul className="mt-2 space-y-1.5">{items.map((x, i) => <li key={i} className="text-[11px] leading-5 text-slate-700">• {x}</li>)}</ul></section>; }

export default function DocumentIntelligence() {
  const [documents, setDocuments] = useState<Document[]>([]);
  const [file, setFile] = useState<File | null>(null);
  const [busy, setBusy] = useState(false); const [error, setError] = useState(""); const [success, setSuccess] = useState("");
  async function load() { const r = await fetch("/api/documents", { cache: "no-store" }); if (r.ok) setDocuments((await r.json()).documents || []); }
  useEffect(() => { load().catch(() => undefined); }, []);
  async function upload(e: React.FormEvent) { e.preventDefault(); if (!file) return; setBusy(true); setError(""); setSuccess(""); try { const b = new FormData(); b.append("file", file); const r = await fetch("/api/documents", { method: "POST", body: b }); const d = await r.json(); if (!r.ok) throw new Error(d?.error || "Unable to analyze report"); setSuccess(d.workflow?.triggered ? "Report analyzed, saved and routed for workflow coordination." : "Report analyzed and saved. Human review is required before clinical action."); setFile(null); const input = document.getElementById("report-file") as HTMLInputElement | null; if (input) input.value = ""; await load(); } catch (e) { setError(e instanceof Error ? e.message : "Unable to analyze report"); } finally { setBusy(false); } }

  return <div className="space-y-6">
    <div className="glass rounded-[30px] p-6 md:p-8 print:hidden">
      <div className="flex flex-col gap-4 md:flex-row md:items-start md:justify-between"><div><p className="text-xs font-bold uppercase tracking-[.16em] text-[var(--care)]">AI document intelligence</p><h2 className="mt-1 font-display text-2xl font-extrabold">Upload a patient report.</h2><p className="mt-2 max-w-2xl text-sm leading-6 text-[var(--muted)]">MediSync extracts evidence, standardizes the source record and prepares it for authorized clinical review.</p></div><span className="rounded-full bg-[var(--care-soft)] px-3 py-1.5 text-[10px] font-bold uppercase tracking-wider text-[var(--care)]">Human-in-the-loop</span></div>
      <form onSubmit={upload} className="mt-7 rounded-[24px] border border-dashed border-black/10 bg-white/65 p-5 md:p-6"><label htmlFor="report-file" className="block text-sm font-bold">Medical report <span className="font-normal text-[var(--muted)]">PDF, PNG, JPEG or WEBP · max 15 MB</span></label><input id="report-file" type="file" accept="application/pdf,image/png,image/jpeg,image/webp" onChange={e => setFile(e.target.files?.[0] ?? null)} className="mt-4 block w-full rounded-2xl border border-black/10 bg-white px-4 py-3 text-sm" />{file && <p className="mt-2 text-xs text-[var(--muted)]">Selected: {file.name}</p>}{error && <div className="mt-4 rounded-2xl bg-[var(--danger-soft)] px-4 py-3 text-sm font-semibold text-[var(--danger)]">{error}</div>}{success && <div className="mt-4 rounded-2xl bg-[var(--care-soft)] px-4 py-3 text-sm font-semibold text-[var(--care)]">{success}</div>}<button disabled={!file || busy} className="mt-5 flex w-full items-center justify-between rounded-2xl bg-[var(--ink)] px-5 py-4 text-sm font-bold text-white shadow-xl disabled:cursor-not-allowed disabled:opacity-45"><span>{busy ? "Uploading, processing and analyzing…" : "Analyze report"}</span><span>→</span></button></form>
    </div>

    {documents.length > 0 && <div className="space-y-8">{documents.map(doc => { const a = doc.metadata?.ai_analysis; const recordId = `MSR-${doc.id.slice(0, 8).toUpperCase()}`; return <article key={doc.id} className="mx-auto w-full max-w-[860px] overflow-hidden bg-[#eef3f3] shadow-[0_30px_90px_rgba(4,38,42,.18)] print:max-w-none print:shadow-none">
      {a ? <>
        <div className="relative min-h-[145px] overflow-hidden bg-[#075e66] px-7 py-7 text-white md:px-10">
          <div className="absolute -right-20 -top-24 h-64 w-[78%] rounded-[50%] border-[28px] border-[#0b8791]/70" />
          <div className="absolute -right-28 top-4 h-48 w-[76%] rounded-[50%] border-[20px] border-[#13a6b2]/55" />
          <div className="absolute -left-20 bottom-[-115px] h-52 w-[75%] rounded-[50%] border-[22px] border-[#063f47]/90" />
          <div className="relative z-10 flex items-start justify-between gap-6">
            <div className="flex items-center gap-4"><div className="flex h-14 w-14 items-center justify-center rounded-sm bg-white text-[#075e66] shadow-lg"><span className="text-5xl font-light leading-none">+</span></div><div><p className="text-[25px] font-black leading-none tracking-[-.03em]">MEDISYNC</p><p className="mt-1 text-[10px] font-bold uppercase tracking-[.28em] text-white/85">HEALTHCARE RECORD SYSTEM</p></div></div>
            <div className="pt-1 text-right"><p className="text-[16px] font-black uppercase tracking-wide">Standardized Record</p><p className="mt-1 text-[9px] font-semibold uppercase tracking-[.2em] text-white/75">Evidence-based · Human review</p><p className="mt-2 text-[9px] text-white/65">Record ID: {recordId}</p></div>
          </div>
        </div>

        <div className="bg-[#edf4f5] px-7 pb-10 pt-7 md:px-12">
          <div className="text-center"><p className="text-[10px] font-bold uppercase tracking-[.3em] text-[#0b5960]">MEDISYNC STANDARDIZED MEDICAL RECORD</p><h3 className="mt-2 font-serif text-[27px] font-black uppercase tracking-[.12em] text-[#073f45]">Clinical Evidence Report</h3><div className="mx-auto mt-3 h-px w-28 bg-[#0b5960]/30" /></div>

          <div className="mt-7 grid gap-0 border border-[#0b5960]/25 bg-white/55 sm:grid-cols-2 lg:grid-cols-4">
            <div className="border-b border-[#0b5960]/15 p-3 sm:border-r"><p className="text-[8px] font-bold uppercase tracking-[.16em] text-[#57777a]">Patient</p><p className="mt-1 text-[11px] font-bold text-[#123f44]">Patient record</p></div>
            <div className="border-b border-[#0b5960]/15 p-3 lg:border-r"><p className="text-[8px] font-bold uppercase tracking-[.16em] text-[#57777a]">Report date</p><p className="mt-1 text-[11px] font-bold text-[#123f44]">{a.report_date || "Not reported"}</p></div>
            <div className="border-b border-[#0b5960]/15 p-3 sm:border-r lg:border-b-0"><p className="text-[8px] font-bold uppercase tracking-[.16em] text-[#57777a]">Document type</p><p className="mt-1 text-[11px] font-bold text-[#123f44]">{a.document_type || "Medical report"}</p></div>
            <div className="p-3"><p className="text-[8px] font-bold uppercase tracking-[.16em] text-[#57777a]">Source</p><p className="mt-1 truncate text-[11px] font-bold text-[#123f44]" title={doc.original_filename}>{doc.original_filename}</p></div>
          </div>

          <div className="mt-7"><h4 className="text-[25px] font-serif font-black text-[#073f45]">Clinical Summary</h4><div className="mt-2 h-px bg-[#0b5960]/25" /><p className="mt-4 text-[12px] leading-6 text-slate-700">{a.summary || "No summary was reported in the source document."}</p></div>

          <div className="mt-7"><h4 className="text-[25px] font-serif font-black text-[#073f45]">Documented Findings</h4><div className="mt-2 h-px bg-[#0b5960]/25" />{a.findings?.length ? <div className="mt-4 overflow-hidden border border-[#0b5960]/20 bg-white/60"><div className="grid grid-cols-[1.2fr_.8fr_1fr] border-b border-[#0b5960]/15 bg-[#075e66] px-3 py-2 text-[8px] font-black uppercase tracking-[.12em] text-white"><span>Finding</span><span>Reported value</span><span>Reference / status</span></div>{a.findings.map((f, i) => <div key={`${f.item}-${i}`} className="grid grid-cols-[1.2fr_.8fr_1fr] gap-2 border-b border-[#0b5960]/10 px-3 py-3 last:border-0"><div><p className="text-[11px] font-bold text-[#183f43]">{f.item}</p><p className="mt-1 text-[9px] leading-4 text-slate-500">{f.evidence}</p></div><p className="text-[11px] font-semibold text-[#183f43]">{f.value || "Not reported"}</p><div><p className="text-[9px] font-bold uppercase tracking-wide text-[#527073]">{statusLabel(f.status)}</p>{f.reference_range && <p className="mt-1 text-[9px] leading-4 text-slate-500">{f.reference_range}</p>}</div></div>)}</div> : <p className="mt-3 text-[11px] text-slate-600">No structured findings were reported.</p>}</div>

          <div className="mt-7 grid gap-4 sm:grid-cols-3"><div className="border-t-2 border-[#0b5960] pt-2"><p className="text-[8px] font-bold uppercase tracking-[.16em] text-[#57777a]">Specialty hint</p><p className="mt-1 text-[11px] font-bold text-[#123f44]">{a.specialty_hint || "General review"}</p></div><div className="border-t-2 border-[#0b5960] pt-2"><p className="text-[8px] font-bold uppercase tracking-[.16em] text-[#57777a]">Workflow</p><p className="mt-1 text-[11px] font-bold text-[#123f44]">{a.workflow || "DOCUMENT"}</p></div><div className="border-t-2 border-[#0b5960] pt-2"><p className="text-[8px] font-bold uppercase tracking-[.16em] text-[#57777a]">AI confidence</p><p className="mt-1 text-[11px] font-bold text-[#123f44]">{typeof a.confidence === "number" ? `${Math.round(a.confidence * 100)}%` : "—"}</p></div></div>

          <Section title="Key observations" items={a.key_observations} /><Section title="Positive / supportive findings" items={a.supportive_findings} /><Section title="Possible associations — not a diagnosis" items={a.possible_associations} /><Section title="Symptoms potentially associated with documented findings" items={a.symptom_associations} /><Section title="Limitations / concerns" items={a.limitations_and_concerns} /><Section title="Red flags documented in the source" items={a.red_flags} /><Section title="Questions to discuss with your clinician" items={a.questions_for_clinician} />

          <div className="mt-8 border-t border-[#0b5960]/25 pt-6"><div className="flex items-end justify-between gap-8"><div><p className="text-[9px] font-black uppercase tracking-[.18em] text-[#0b5960]">Authorized clinical review</p><p className="mt-1 text-[11px] font-bold text-[#183f43]">Pending clinician review</p><p className="mt-1 max-w-md text-[9px] leading-4 text-slate-500">This is a MediSync standardized evidence record. It is not a prescription, diagnosis, or treatment order.</p></div><div className="w-44 text-center"><div className="border-b border-[#173f43]/60" /><p className="mt-1 text-[8px] font-bold uppercase tracking-[.12em] text-[#57777a]">Clinician review / signature</p></div></div></div>
        </div>

        <footer className="bg-[#075e66] px-7 py-5 text-white md:px-10"><div className="flex flex-col gap-2 sm:flex-row sm:items-center sm:justify-between"><p className="text-[10px] font-black uppercase tracking-[.2em]">MEDISYNC HEALTHCARE RECORD SYSTEM</p><p className="text-[9px] font-semibold text-white/75">AI-assisted · Human review required</p></div><p className="mt-2 max-w-3xl text-[9px] leading-4 text-white/65">Original source documents remain the authoritative evidence. MediSync standardizes documented information for care coordination and does not independently diagnose, prescribe, change medication, or make autonomous clinical decisions.</p></footer>
      </> : <div className="p-8"><p className="text-sm font-bold">Processing status: {doc.processing_status || doc.ocr_status}</p><p className="mt-2 text-sm text-[var(--muted)]">{doc.processing_error || "Your document is being processed. The completed structured analysis will appear here."}</p></div>}
    </article>; })}</div>}
  </div>;
}
