create or replace function public.create_request_with_audit(p_request_id text,p_patient_id uuid,p_description text,p_request_source text,p_document_uploaded boolean,p_actor_user_id uuid,p_actor_role text) returns public.requests language plpgsql security definer set search_path=public as $$ declare v_row public.requests; begin insert into public.requests(request_id,patient_id,description,request_source,document_uploaded) values(p_request_id,p_patient_id,p_description,p_request_source,p_document_uploaded) returning * into v_row; insert into public.audit_logs(actor_user_id,actor_role,action,entity_type,entity_id,request_id,new_state,metadata) values(p_actor_user_id,p_actor_role,'REQUEST_CREATED','request',v_row.id,v_row.id,to_jsonb('CREATED'::text),jsonb_build_object('request_id',v_row.request_id,'request_source',v_row.request_source)); return v_row; end; $$;

create or replace function public.update_request_stage_with_audit(p_request_db_id uuid,p_expected_stage text,p_expected_updated_at timestamptz,p_next_stage text,p_actor_user_id uuid,p_actor_role text) returns public.requests language plpgsql security definer set search_path=public as $$ declare v_row public.requests; begin update public.requests set workflow_stage=p_next_stage where id=p_request_db_id and workflow_stage=p_expected_stage and updated_at=p_expected_updated_at returning * into v_row; if not found then raise exception 'CONCURRENT_MODIFICATION'; end if; insert into public.audit_logs(actor_user_id,actor_role,action,entity_type,entity_id,request_id,previous_state,new_state) values(p_actor_user_id,p_actor_role,'REQUEST_STAGE_CHANGED','request',v_row.id,v_row.id,to_jsonb(p_expected_stage::text),to_jsonb(p_next_stage::text)); return v_row; end; $$;

create or replace function public.classify_request_with_audit(p_request_db_id uuid,p_expected_updated_at timestamptz,p_request_type text,p_ai_classification jsonb,p_ai_confidence numeric,p_ai_reason text,p_actor_user_id uuid,p_actor_role text) returns public.requests language plpgsql security definer set search_path=public as $$ declare v_row public.requests; begin update public.requests set request_type=p_request_type,workflow_stage='CLASSIFIED',ai_classification=p_ai_classification,ai_confidence=p_ai_confidence,ai_reason=p_ai_reason where id=p_request_db_id and workflow_stage='CREATED' and updated_at=p_expected_updated_at returning * into v_row; if not found then raise exception 'CONCURRENT_MODIFICATION'; end if; insert into public.audit_logs(actor_user_id,actor_role,action,entity_type,entity_id,request_id,previous_state,new_state,metadata) values(p_actor_user_id,p_actor_role,'REQUEST_CLASSIFIED','request',v_row.id,v_row.id,to_jsonb('CREATED'::text),to_jsonb('CLASSIFIED'::text),jsonb_build_object('request_type',p_request_type,'confidence',p_ai_confidence)); return v_row; end; $$;

create or replace function public.create_referral_with_audit(p_referral_id text,p_request_id uuid,p_hospital_id uuid,p_specialist_id uuid,p_clinical_summary text,p_reason text,p_actor_user_id uuid,p_actor_role text) returns public.referrals language plpgsql security definer set search_path=public as $$ declare v_row public.referrals; begin insert into public.referrals(referral_id,request_id,hospital_id,specialist_id,clinical_summary,reason) values(p_referral_id,p_request_id,p_hospital_id,p_specialist_id,p_clinical_summary,p_reason) returning * into v_row; insert into public.audit_logs(actor_user_id,actor_role,action,entity_type,entity_id,request_id,new_state,metadata) values(p_actor_user_id,p_actor_role,'REFERRAL_CREATED','referral',v_row.id,v_row.request_id,to_jsonb(v_row.status::text),jsonb_build_object('referral_id',v_row.referral_id,'hospital_id',v_row.hospital_id,'specialist_id',v_row.specialist_id)); return v_row; end; $$;

create or replace function public.transition_referral_with_audit(p_referral_db_id uuid,p_expected_status text,p_expected_updated_at timestamptz,p_next_status text,p_received_at timestamptz,p_reviewed_at timestamptz,p_decided_at timestamptz,p_actor_user_id uuid,p_actor_role text) returns public.referrals language plpgsql security definer set search_path=public as $$ declare v_row public.referrals; begin update public.referrals set status=p_next_status,received_at=coalesce(p_received_at,received_at),reviewed_at=coalesce(p_reviewed_at,reviewed_at),decided_at=coalesce(p_decided_at,decided_at) where id=p_referral_db_id and status=p_expected_status and updated_at=p_expected_updated_at returning * into v_row; if not found then raise exception 'CONCURRENT_MODIFICATION'; end if; insert into public.audit_logs(actor_user_id,actor_role,action,entity_type,entity_id,request_id,previous_state,new_state,metadata) values(p_actor_user_id,p_actor_role,'REFERRAL_STATUS_CHANGED','referral',v_row.id,v_row.request_id,to_jsonb(p_expected_status::text),to_jsonb(p_next_status::text),jsonb_build_object('referral_id',v_row.referral_id)); return v_row; end; $$;
