-- Seed 1/3 from Tamil_Nadu_Hospitals_3_Tier.xlsx
alter table public.hospitals add column if not exists medisync_tier text check (medisync_tier in ('Tier 1', 'Tier 2', 'Tier 3'));
alter table public.hospitals add column if not exists tier_basis text;
alter table public.hospitals add column if not exists catalog_metadata jsonb not null default '{}'::jsonb;
create index if not exists hospitals_medisync_tier_idx on public.hospitals(medisync_tier);

insert into public.hospitals (name, city, state, country, operational_status, medisync_tier, tier_basis, catalog_metadata) select 'Rajiv Gandhi Government General Hospital (Madras Medical College)', 'Chennai', 'Tamil Nadu', 'India', 'ACTIVE', 'Tier 1', 'By Hospital Type', jsonb_build_object('ownership','Government','district','Chennai','notes','Largest govt hospital in TN; major teaching hospital','source','Tamil_Nadu_Hospitals_3_Tier.xlsx') where not exists (select 1 from public.hospitals h where lower(h.name)=lower('Rajiv Gandhi Government General Hospital (Madras Medical College)') and lower(coalesce(h.city,''))=lower('Chennai'));
insert into public.hospitals (name, city, state, country, operational_status, medisync_tier, tier_basis, catalog_metadata) select 'Government Stanley Medical College Hospital', 'Chennai', 'Tamil Nadu', 'India', 'ACTIVE', 'Tier 1', 'By Hospital Type', jsonb_build_object('ownership','Government','district','Chennai','notes','Teaching hospital, North Chennai','source','Tamil_Nadu_Hospitals_3_Tier.xlsx') where not exists (select 1 from public.hospitals h where lower(h.name)=lower('Government Stanley Medical College Hospital') and lower(coalesce(h.city,''))=lower('Chennai'));
insert into public.hospitals (name, city, state, country, operational_status, medisync_tier, tier_basis, catalog_metadata) select 'Government Kilpauk Medical College Hospital', 'Chennai', 'Tamil Nadu', 'India', 'ACTIVE', 'Tier 1', 'By Hospital Type', jsonb_build_object('ownership','Government','district','Chennai','notes','Teaching hospital','source','Tamil_Nadu_Hospitals_3_Tier.xlsx') where not exists (select 1 from public.hospitals h where lower(h.name)=lower('Government Kilpauk Medical College Hospital') and lower(coalesce(h.city,''))=lower('Chennai'));
insert into public.hospitals (name, city, state, country, operational_status, medisync_tier, tier_basis, catalog_metadata) select 'Government Omandurar Medical College Hospital', 'Chennai', 'Tamil Nadu', 'India', 'ACTIVE', 'Tier 1', 'By Hospital Type', jsonb_build_object('ownership','Government','district','Chennai','notes','Teaching hospital','source','Tamil_Nadu_Hospitals_3_Tier.xlsx') where not exists (select 1 from public.hospitals h where lower(h.name)=lower('Government Omandurar Medical College Hospital') and lower(coalesce(h.city,''))=lower('Chennai'));
insert into public.hospitals (name, city, state, country, operational_status, medisync_tier, tier_basis, catalog_metadata) select 'Institute of Child Health & Hospital for Children, Egmore', 'Chennai', 'Tamil Nadu', 'India', 'ACTIVE', 'Tier 1', 'By Hospital Type', jsonb_build_object('ownership','Government','district','Chennai','notes','Pediatric referral centre','source','Tamil_Nadu_Hospitals_3_Tier.xlsx') where not exists (select 1 from public.hospitals h where lower(h.name)=lower('Institute of Child Health & Hospital for Children, Egmore') and lower(coalesce(h.city,''))=lower('Chennai'));
insert into public.hospitals (name, city, state, country, operational_status, medisync_tier, tier_basis, catalog_metadata) select 'Coimbatore Medical College Hospital', 'Coimbatore', 'Tamil Nadu', 'India', 'ACTIVE', 'Tier 1', 'By Hospital Type', jsonb_build_object('ownership','Government','district','Coimbatore','notes','Teaching hospital','source','Tamil_Nadu_Hospitals_3_Tier.xlsx') where not exists (select 1 from public.hospitals h where lower(h.name)=lower('Coimbatore Medical College Hospital') and lower(coalesce(h.city,''))=lower('Coimbatore'));
insert into public.hospitals (name, city, state, country, operational_status, medisync_tier, tier_basis, catalog_metadata) select 'Government Rajaji Hospital (Madurai Medical College)', 'Madurai', 'Tamil Nadu', 'India', 'ACTIVE', 'Tier 1', 'By Hospital Type', jsonb_build_object('ownership','Government','district','Madurai','notes','Teaching hospital, South TN referral','source','Tamil_Nadu_Hospitals_3_Tier.xlsx') where not exists (select 1 from public.hospitals h where lower(h.name)=lower('Government Rajaji Hospital (Madurai Medical College)') and lower(coalesce(h.city,''))=lower('Madurai'));
insert into public.hospitals (name, city, state, country, operational_status, medisync_tier, tier_basis, catalog_metadata) select 'Mahatma Gandhi Memorial Govt Hospital (KAP Viswanatham Medical College)', 'Tiruchirappalli', 'Tamil Nadu', 'India', 'ACTIVE', 'Tier 1', 'By Hospital Type', jsonb_build_object('ownership','Government','district','Tiruchirappalli','notes','Teaching hospital','source','Tamil_Nadu_Hospitals_3_Tier.xlsx') where not exists (select 1 from public.hospitals h where lower(h.name)=lower('Mahatma Gandhi Memorial Govt Hospital (KAP Viswanatham Medical College)') and lower(coalesce(h.city,''))=lower('Tiruchirappalli'));
insert into public.hospitals (name, city, state, country, operational_status, medisync_tier, tier_basis, catalog_metadata) select 'Government Thanjavur Medical College Hospital', 'Thanjavur', 'Tamil Nadu', 'India', 'ACTIVE', 'Tier 1', 'By Hospital Type', jsonb_build_object('ownership','Government','district','Thanjavur','notes','Teaching hospital','source','Tamil_Nadu_Hospitals_3_Tier.xlsx') where not exists (select 1 from public.hospitals h where lower(h.name)=lower('Government Thanjavur Medical College Hospital') and lower(coalesce(h.city,''))=lower('Thanjavur'));
insert into public.hospitals (name, city, state, country, operational_status, medisync_tier, tier_basis, catalog_metadata) select 'Government Tirunelveli Medical College Hospital', 'Tirunelveli', 'Tamil Nadu', 'India', 'ACTIVE', 'Tier 1', 'By Hospital Type', jsonb_build_object('ownership','Government','district','Tirunelveli','notes','Teaching hospital','source','Tamil_Nadu_Hospitals_3_Tier.xlsx') where not exists (select 1 from public.hospitals h where lower(h.name)=lower('Government Tirunelveli Medical College Hospital') and lower(coalesce(h.city,''))=lower('Tirunelveli'));
insert into public.hospitals (name, city, state, country, operational_status, medisync_tier, tier_basis, catalog_metadata) select 'Government Mohan Kumaramangalam Medical College Hospital', 'Salem', 'Tamil Nadu', 'India', 'ACTIVE', 'Tier 1', 'By Hospital Type', jsonb_build_object('ownership','Government','district','Salem','notes','Teaching hospital','source','Tamil_Nadu_Hospitals_3_Tier.xlsx') where not exists (select 1 from public.hospitals h where lower(h.name)=lower('Government Mohan Kumaramangalam Medical College Hospital') and lower(coalesce(h.city,''))=lower('Salem'));
insert into public.hospitals (name, city, state, country, operational_status, medisync_tier, tier_basis, catalog_metadata) select 'Government Vellore Medical College Hospital', 'Vellore', 'Tamil Nadu', 'India', 'ACTIVE', 'Tier 1', 'By Hospital Type', jsonb_build_object('ownership','Government','district','Vellore','notes','Teaching hospital','source','Tamil_Nadu_Hospitals_3_Tier.xlsx') where not exists (select 1 from public.hospitals h where lower(h.name)=lower('Government Vellore Medical College Hospital') and lower(coalesce(h.city,''))=lower('Vellore'));
insert into public.hospitals (name, city, state, country, operational_status, medisync_tier, tier_basis, catalog_metadata) select 'Christian Medical College (CMC) Hospital', 'Vellore', 'Tamil Nadu', 'India', 'ACTIVE', 'Tier 1', 'By Hospital Type', jsonb_build_object('ownership','Private (Trust)','district','Vellore','notes','Nationally renowned tertiary referral centre','source','Tamil_Nadu_Hospitals_3_Tier.xlsx') where not exists (select 1 from public.hospitals h where lower(h.name)=lower('Christian Medical College (CMC) Hospital') and lower(coalesce(h.city,''))=lower('Vellore'));
insert into public.hospitals (name, city, state, country, operational_status, medisync_tier, tier_basis, catalog_metadata) select 'AIIMS Madurai', 'Madurai', 'Tamil Nadu', 'India', 'ACTIVE', 'Tier 1', 'By Hospital Type', jsonb_build_object('ownership','Central Government','district','Madurai','notes','Under Central Govt (AIIMS scheme)','source','Tamil_Nadu_Hospitals_3_Tier.xlsx') where not exists (select 1 from public.hospitals h where lower(h.name)=lower('AIIMS Madurai') and lower(coalesce(h.city,''))=lower('Madurai'));
insert into public.hospitals (name, city, state, country, operational_status, medisync_tier, tier_basis, catalog_metadata) select 'Apollo Hospitals, Greams Road', 'Chennai', 'Tamil Nadu', 'India', 'ACTIVE', 'Tier 1', 'By Hospital Type', jsonb_build_object('ownership','Private (Corporate)','district','Chennai','notes','Flagship of Apollo chain','source','Tamil_Nadu_Hospitals_3_Tier.xlsx') where not exists (select 1 from public.hospitals h where lower(h.name)=lower('Apollo Hospitals, Greams Road') and lower(coalesce(h.city,''))=lower('Chennai'));
insert into public.hospitals (name, city, state, country, operational_status, medisync_tier, tier_basis, catalog_metadata) select 'MIOT International', 'Chennai', 'Tamil Nadu', 'India', 'ACTIVE', 'Tier 1', 'By Hospital Type', jsonb_build_object('ownership','Private (Corporate)','district','Chennai','notes','Multi-organ transplant, ortho, cardiac','source','Tamil_Nadu_Hospitals_3_Tier.xlsx') where not exists (select 1 from public.hospitals h where lower(h.name)=lower('MIOT International') and lower(coalesce(h.city,''))=lower('Chennai'));
insert into public.hospitals (name, city, state, country, operational_status, medisync_tier, tier_basis, catalog_metadata) select 'Fortis Malar Hospital', 'Chennai', 'Tamil Nadu', 'India', 'ACTIVE', 'Tier 1', 'By Hospital Type', jsonb_build_object('ownership','Private (Corporate)','district','Chennai','notes','Multi-specialty tertiary care','source','Tamil_Nadu_Hospitals_3_Tier.xlsx') where not exists (select 1 from public.hospitals h where lower(h.name)=lower('Fortis Malar Hospital') and lower(coalesce(h.city,''))=lower('Chennai'));
insert into public.hospitals (name, city, state, country, operational_status, medisync_tier, tier_basis, catalog_metadata) select 'MGM Healthcare', 'Chennai', 'Tamil Nadu', 'India', 'ACTIVE', 'Tier 1', 'By Hospital Type', jsonb_build_object('ownership','Private (Corporate)','district','Chennai','notes','Heart & lung transplant centre','source','Tamil_Nadu_Hospitals_3_Tier.xlsx') where not exists (select 1 from public.hospitals h where lower(h.name)=lower('MGM Healthcare') and lower(coalesce(h.city,''))=lower('Chennai'));
insert into public.hospitals (name, city, state, country, operational_status, medisync_tier, tier_basis, catalog_metadata) select 'SIMS Hospital', 'Chennai', 'Tamil Nadu', 'India', 'ACTIVE', 'Tier 1', 'By Hospital Type', jsonb_build_object('ownership','Private (Corporate)','district','Chennai','notes','Multi-organ transplant centre','source','Tamil_Nadu_Hospitals_3_Tier.xlsx') where not exists (select 1 from public.hospitals h where lower(h.name)=lower('SIMS Hospital') and lower(coalesce(h.city,''))=lower('Chennai'));
insert into public.hospitals (name, city, state, country, operational_status, medisync_tier, tier_basis, catalog_metadata) select 'Rela Hospital', 'Chennai', 'Tamil Nadu', 'India', 'ACTIVE', 'Tier 1', 'By Hospital Type', jsonb_build_object('ownership','Private (Corporate)','district','Chennai','notes','Liver transplant / quaternary care','source','Tamil_Nadu_Hospitals_3_Tier.xlsx') where not exists (select 1 from public.hospitals h where lower(h.name)=lower('Rela Hospital') and lower(coalesce(h.city,''))=lower('Chennai'));
insert into public.hospitals (name, city, state, country, operational_status, medisync_tier, tier_basis, catalog_metadata) select 'Gleneagles Global Health City', 'Chennai', 'Tamil Nadu', 'India', 'ACTIVE', 'Tier 1', 'By Hospital Type', jsonb_build_object('ownership','Private (Corporate)','district','Chennai','notes','Multi-specialty, transplant care','source','Tamil_Nadu_Hospitals_3_Tier.xlsx') where not exists (select 1 from public.hospitals h where lower(h.name)=lower('Gleneagles Global Health City') and lower(coalesce(h.city,''))=lower('Chennai'));
